# Generated by Django 4.2.11 on 2024-05-26 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Logout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default=' ', null=True, upload_to='Login_Logout/media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentImage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
