# Generated by Django 4.2.11 on 2024-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Logout', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_image',
            name='Image',
            field=models.ImageField(blank=True, default='socialmedia/pro.png', null=True, upload_to='Login_Logout/media/'),
        ),
    ]
