# Generated by Django 4.2.11 on 2024-05-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Logout', '0003_alter_student_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_image',
            name='Image',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='Login_Logout/media/'),
        ),
    ]
