# Generated by Django 4.2.11 on 2024-05-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Logout', '0004_alter_student_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_image',
        ),
    ]
